In [7]:
import pickle
import numpy as np

In [6]:
!ls

classifier.pickle  sample_data	sc.pickle


In [2]:
!wget https://github.com/saikiran123456/REST_API_Classification_Project/raw/Machine-learning/classifier.pickle

--2023-04-18 13:06:55--  https://github.com/saikiran123456/REST_API_Classification_Project/raw/Machine-learning/classifier.pickle
Resolving github.com (github.com)... 192.30.255.113
Connecting to github.com (github.com)|192.30.255.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/saikiran123456/REST_API_Classification_Project/Machine-learning/classifier.pickle [following]
--2023-04-18 13:06:55--  https://raw.githubusercontent.com/saikiran123456/REST_API_Classification_Project/Machine-learning/classifier.pickle
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2102 (2.1K) [application/octet-stream]
Saving to: ‘classifier.pickle’

classifier.pickle   100%[===================>]   2.05K  --.-KB/s  

In [3]:
!wget https://github.com/saikiran123456/REST_API_Classification_Project/raw/Machine-learning/sc.pickle

--2023-04-18 13:07:18--  https://github.com/saikiran123456/REST_API_Classification_Project/raw/Machine-learning/sc.pickle
Resolving github.com (github.com)... 192.30.255.113
Connecting to github.com (github.com)|192.30.255.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/saikiran123456/REST_API_Classification_Project/Machine-learning/sc.pickle [following]
--2023-04-18 13:07:18--  https://raw.githubusercontent.com/saikiran123456/REST_API_Classification_Project/Machine-learning/sc.pickle
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 497 [application/octet-stream]
Saving to: ‘sc.pickle’

sc.pickle           100%[===================>]     497  --.-KB/s    in 0s      

2023-04-18 13:07:18 (16.7

In [4]:
!ls

classifier.pickle  sample_data	sc.pickle


In [8]:
classifier_colab = pickle.load(open('classifier.pickle', 'rb'))

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:318: UserWarning: Trying to unpickle estimator KNeighborsClassifier from version 1.1.3 when using version 1.2.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(


In [9]:
scaler_colab = pickle.load(open('sc.pickle', 'rb'))

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:318: UserWarning: Trying to unpickle estimator StandardScaler from version 1.1.3 when using version 1.2.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(


In [10]:
## Next we will use the classifier and scalar objects to do the prediction.

In [11]:
## to Predict whether a Customer with AGE = 40 and Salary=20000 with Purchase or Not

In [12]:
new_pred = classifier_colab.predict(scaler_colab.transform(np.array([[40,20000]])))
new_pred

array([0])

In [13]:
new_prediction_proba = classifier_colab.predict_proba(scaler_colab.transform(np.array([[40,20000]])))[:,1]
new_prediction_proba

array([0.2])

In [14]:
## Predict whether a Customer with AGE = 42 and Salary=50000 with Purchase or Not

In [15]:
new_pred = classifier_colab.predict(scaler_colab.transform(np.array([[42,50000]])))
new_pred

array([1])

In [16]:
new_pred_proba = classifier_colab.predict_proba(scaler_colab.transform(np.array([[42,50000]])))[:,1]
new_pred_proba

array([0.8])

In [19]:
# This is how you can train models in one environment and run them in a completely new environment.