In [1]:
import pickle
import numpy as np # As we are feeding the data in NUMPY array format

# Deserialize and Store the Classifier & Scaler in their Local Object

In [2]:
local_classifier = pickle.load(open('classifier.pickle','rb'))
local_scaler = pickle.load(open('sc.pickle','rb'))

## Using "local_classifier" and "local_scaler", 

## to Predict whether a Customer with AGE = 40 and Salary=20000 with Purchase or Not

**Prior Converting the New Data into Numpy Array, pretty much we did while we trained the data**

In [4]:
new_pred = local_classifier.predict(local_scaler.transform(np.array([[40,20000]])))
new_pred

array([0], dtype=int64)

- Which means the Customer will Not Purchase

**Let's Check the Probability for the Same!**

In [5]:
new_prediction_proba = local_classifier.predict_proba(local_scaler.transform(np.array([[40,20000]])))[:,1]
new_prediction_proba

array([0.2])

## Predict whether a Customer with AGE = 42 and Salary=50000 with Purchase or Not

In [6]:
new_pred = local_classifier.predict(local_scaler.transform(np.array([[42,50000]])))
new_pred

array([1], dtype=int64)

In [7]:
new_pred_proba = local_classifier.predict_proba(local_scaler.transform(np.array([[42,50000]])))[:,1]
new_pred_proba

array([0.8])